### ISSUE TITLE
Error:代理错误: All connection attempts failed

### ISSUE THREAD

**Issue by whale-song** [kexue-z/nonebot-plugin-setu-now#1]
控制台信息如下：

12-10 19:50:11 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_setu_now, type=message, priority=1, temp=False>
12-10 19:50:11 [INFO] nonebot_plugin_setu_now | key=,r18=False
12-10 19:50:15 [INFO] nonebot_plugin_setu_now | {'error': '', 'data': [{'pid': 94520024, 'p': 1, 'uid': 31938023, 'title': '事前ナイツ', 'author': 'Kokihanada', 'r18': False, 'width': 2894, 'height': 4093, 'tags': ['R-18', 'おっぱい', '欧派', 'アークナイツ', '明日方舟', 'Arknights', 'プラチナ(アークナイツ)', '白金 （明日方舟）', 'ウタゲ(アークナイツ)', '宴（明日方舟）'], 'ext': 'jpg', 'uploadDate': 1638446417000, 'urls': {'regular': 'https://i.pixiv.cat/img-master/img/2021/12/02/21/00/17/94520024_p1_master1200.jpg'}}]}
12-10 19:50:15 [WARNING] nonebot_plugin_setu_now | All connection attempts failed

**Comment by kexue-z** [comment]
![图片](https://user-images.githubusercontent.com/71873002/145570314-0c706a7e-45d2-4f3a-86ab-b29273092ad1.png)
请设置代理

**Comment by whale-song** [comment]
> ![图片](https://user-images.githubusercontent.com/71873002/145570314-0c706a7e-45d2-4f3a-86ab-b29273092ad1.png) 请设置代理

请问setu_porxy的数据格式，尝试xxx.xxx.xxx.xxx:xxxx的格式后报错Error:<class 'ValueError'> Unknown scheme for proxy URL URL

**Comment by kexue-z** [comment]
http://ip:port

**Comment by whale-song** [comment]
昨天用代理一直没跑通，今天试着不挂代理跑，报api错误
![image](https://user-images.githubusercontent.com/43376589/145670602-4daae9b0-877e-4a8c-9588-85479074ec53.png)
控制台无报错，看了一下lolicon那边的可用性似乎没出问题
![image](https://user-images.githubusercontent.com/43376589/145670624-c92d6984-105a-4f54-b30c-7163667c33a2.png)

**Comment by kexue-z** [comment]
更新了新版本`0.0.4` 再试试 获取lolicon API的时候会自动调用环境变量中的全局代理
而获取图片的时候 如不配置 `setu_porxy=http://ip:port` 则会使用 `http://127.0.0.1:7890` 作为代理
后续更新会统一代理方式

**Comment by whale-song** [comment]
使用默认的127.0.0.1:7890还是会报代理错误:All connection attempts failed

**Comment by kexue-z** [comment]
啊这... 你确定你的代理正常启用吗?
在终端使用 `export  http_proxy=http://127.0.0.1:7890` 然后 `ping google.com` 试试看

**Comment by whale-song** [comment]
ping不通.. 跟服务器提供商有关吗，用的是腾讯云的服务器

**Comment by kexue-z** [comment]
那就是你代理的问题了( 
~~跟我没什么关系~~
