### ISSUE TITLE
a problem in use 

### ISSUE THREAD

**Issue by shelter132** [kexue-z/nonebot-plugin-setu-now#13]
json.decoder.JSONDecodeError: Extra data: line 1 column 39 (char 38)
这是什么问题？在更新后使用时出现这种报错...网上找了下原因，但自己水平不大够，没法解决......
![QJTJQ7_I{9RBIT$H5N5~DCG](https://user-images.githubusercontent.com/99066443/159539525-6d6f380e-0d70-4ef9-9fa3-011099764fcf.png)

**Comment by kexue-z** [comment]
把 `data/setu_now/` 文件夹删除试试

**Comment by shelter132** [comment]
> 把 文件夹删除试试`data/setu_now/`

ok,解决了，多谢！
（所以是为啥呢？）

**Comment by kexue-z** [comment]
可能是 `cd.json` 没有写入完毕 导致json文件语法错误
然后 `json.decoder` 就报错
