### ISSUE TITLE
在定时撤回中，如何只让机器人撤回图片，而不去撤回图片相关的信息

### ISSUE THREAD

**Issue by GilgameshSAMA** [kexue-z/nonebot-plugin-setu-now#14]

**Comment by kexue-z** [comment]
把

https://github.com/kexue-z/nonebot-plugin-setu-now/blob/2c338de00481fc868687c19db2814a3667b31c92/nonebot_plugin_setu_now/__init__.py#L83

删了

**Comment by GilgameshSAMA** [comment]
> 

感谢
