### ISSUE TITLE
机器人不回复，debug信息如下

### ISSUE THREAD

**Issue by jesongit** [kexue-z/nonebot-plugin-setu-now#15]
``` 
Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
```

**Comment by jesongit** [comment]
> ```
> Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored
> ```
使用的是 nonebot2，安装方式是 nb-cli 中的 nb plugin install

**Comment by jesongit** [comment]
Event type <class 'nonebot.adapters.onebot.v11.event.GroupMessageEvent'> not match annotation PrivateMessageEvent, ignored
试了下，群聊和私聊的类是反了么？

**Comment by kexue-z** [comment]
这是什么截LOG艺术，我看不懂 😥

**Comment by jesongit** [comment]
他就一直打印这一行，我就没截图其他的，前面是正常的加载信息

**Comment by kexue-z** [comment]
那前面import成功了吗

**Comment by jesongit** [comment]
前面的加载信息里面有这个插件，应该算成功吧？我去复制一个完整的日志

**Comment by jesongit** [comment]
![C06)71TQN61X2AKHZL)G_65](https://user-images.githubusercontent.com/29886847/161976021-451a6da8-e2c4-4c2d-b9c3-6554623ed47e.png)
![MYJ3FE{)O WIT13PCK8YF00](https://user-images.githubusercontent.com/29886847/161976038-c23f6b14-ffd8-4639-8fbf-eeac819265c5.png)
第一张是前面加载配置的，后面这张分别是私聊的和群里面发的

**Comment by kexue-z** [comment]
有没有可能 他并不需要on_commend 他是on_regex

**Comment by kexue-z** [comment]
https://github.com/kexue-z/nonebot-plugin-setu-now/issues/6

**Comment by jesongit** [comment]
谢谢大佬，麻烦了，打扰了
