### ISSUE TITLE
占用一下您宝贵的时间，想提一点建议

### ISSUE THREAD

**Issue by shmilyty** [kexue-z/nonebot-plugin-setu-now#16]
抱歉打扰大佬，感觉您的插件很好用！
但是在使用过程中遇到了一些麻烦，具体来说，想要实现两个功能
- ignore某个人的调用命令
- 限制在某个群聊内一天的调用总次数

尝试自己实现，奈何技术不够高，不是很会写，故此求助
谢谢您！

**Comment by kexue-z** [comment]
限制调用次数可以整
忽略某个人的指令这个可以做成别的插件
到时候再整吧

**Comment by shmilyty** [comment]
好的，谢谢答复

**Comment by kexue-z** [comment]
虽然我重写了 发版 `0.2.0` 了 但是你的需求我一个都没有写

因为
- 黑名单可以用 [nonebot-plugin-manager](https://github.com/nonepkg/nonebot-plugin-manager) 代替
- 限制调用次数也应该是其他插件的事情 但是目前没有 所以提了[issue](https://github.com/nonepkg/nonebot-plugin-manager/issues/6) 让别人来写 (我是懒狗)

或者你也可以试试全新的色图 全新的体验（（

**Comment by shmilyty** [comment]
好的，谢谢您！
