### ISSUE TITLE
All connection attempts failed

### ISSUE THREAD

**Issue by Aues6uen11Z** [kexue-z/nonebot-plugin-setu-now#2]
和之前一样的问题，想问问在国内有什么稳定使用的方式吗。不买代理ip的话，手动频繁换免费网站上的短效ip不太现实，我用proxy_pool这个项目自动找ip成功率也很低，这样就无解了吗？有没有什么好办法白嫖还稳定呢（

**Comment by kexue-z** [comment]
试试最新的 `nonebot-plugin-setu-now 0.0.4.2` 采用 `i.pixiv.re` 进行反向代理，我这边不开代理也没问题

**Comment by Aues6uen11Z** [comment]
我pip安装会报错
ERROR: Could not find a version that satisfies the requirement nonebot-plugin-setu-now (from versions: none)
ERROR: No matching distribution found for nonebot-plugin-setu-now
网上查这个错一般是pip版本低，但我去更新说已经是最新的了，可能是我python3.7.3版本低？请问通过pip安装和下载文件后手动放在src/plugins下有区别吗，我现在是通过后者运行的

**Comment by kexue-z** [comment]
`pip3 install -U nonebot-plugin-setu-now==0.0.4.2`

pip 上的一般是我手动打包的 而github上的代码一般随时更新 直接git clone 下来的代码应该也没什么问题

**Comment by Aues6uen11Z** [comment]
那我这里还是获取不到(ಥ_ಥ)

**Comment by kexue-z** [comment]
看看log 或提示

**Comment by Aues6uen11Z** [comment]
01-18 03:02:23 [SUCCESS] nonebot | CQHTTP 2332344854 | [message.group.normal]: Message 623451183 from 861831317@[群:674108658] "涩图"
01-18 03:02:23 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_setu_now, type=message, priority=1, temp=False>
01-18 03:02:23 [INFO] nonebot_plugin_setu_now | key=,r18=False
01-18 03:02:55 [WARNING] nonebot_plugin_setu_now | All connection attempts failed
就跟以前一样，qq里提示API异常All connection attempts failed。不过刚才试的时候也成功过2次，应该算可以了？

**Comment by kexue-z** [comment]
API 异常那就是 `https://api.lolicon.app/setu/v2` 这个网站你可能访问不到或者不稳定

你可以试试在shell里 测试一下 用 `ping` 和 `curl`

**Comment by Aues6uen11Z** [comment]
虽然会间歇抽风，但这样已经可以了，感谢！
