### ISSUE TITLE
关于文件名

### ISSUE THREAD

**Issue by bugcatcapoo** [kexue-z/nonebot-plugin-setu-now#20]
开启了自动保存到本地的功能，结果有一些setu无法发出（有一些还是可以），报错如下：
![image](https://user-images.githubusercontent.com/104308239/166177853-6b5d341f-a656-45a6-9ae0-ab63099ac005.png)
好像以前保存到本地时文件名都是数字，但是现在多了setu名称，可能是因为这个导致无法保存
建议可以将保存的文件名改为当前的时间

**Comment by kexue-z** [comment]
试试创建一个 `data/setur18/` 的目录
