### ISSUE TITLE
貌似是请求超时的问题，在.env里将反代设置为i.pixiv.re后可以正常获取到图片信息，但一段时间后又无法获取了

### ISSUE THREAD

**Issue by 23650** [kexue-z/nonebot-plugin-setu-now#23]
https://paste.ubuntu.com/p/tSX5ZgVRHv/

**Comment by kexue-z** [comment]
看起来是代理挂了 建议把env贴出来看看

**Comment by 23650** [comment]
![捕获](https://user-images.githubusercontent.com/82879659/169686686-1b0b0391-781d-4baa-b096-63bb4d2a64ca.PNG)

**Comment by kexue-z** [comment]
LOG_LEVEL 设置为 DEBUG 看看LOG

**Comment by 23650** [comment]
就等了，从debug看来一条爬到了，一条没爬到，但这两条都没有正确返回图片信息
爬到了——https://paste.ubuntu.com/p/f32kXrjTTz/
没爬到——https://paste.ubuntu.com/p/JqvG28Pw9C/

**Comment by kexue-z** [comment]
这怎么看都是网不好，在相同的环境下 分别ping 一下 `i.pixiv.re` 和 `api.lolicon.app`

**Comment by 23650** [comment]
![D475~ATC4JDGXP~SGXDT8(F](https://user-images.githubusercontent.com/82879659/169695846-f59226ee-82d8-4aaf-bda4-8eb8d026acb1.png)

**Comment by 23650** [comment]
看来确实是延迟问题？

**Comment by Gorge148257** [comment]
是网络问题看来，我刚才的日志里的问题也是这个，也是无法获取图片信息。
刚才在没有调整任何设置的情况下图出来了，此时能够ping通俩个网站

**Comment by Gorge148257** [comment]
是网络问题看来，我这边也是无法获取图片信息，日志里内容和上面是一样的。
刚才在没有调整任何设置的情况下图能够加载，此时能够ping通俩个网站。综上大概就是网络问题。

**Comment by 23650** [comment]
打扰了

**Comment by kexue-z** [comment]
az
