### ISSUE TITLE
两个小建议（？）

### ISSUE THREAD

**Issue by huangusaki** [kexue-z/nonebot-plugin-setu-now#24]
1、最近好像审核有点严，合并发消息经常会被风控，可以尝试下更改图片的大小规避tx审核？我这边试了试把图片随机按一定范围比例内的随机放大缩小就能正常发出合并消息的图片，不然十个合并消息九个都因为风控发不出。

2、偶尔会有返回空图的情况发生，不确定是不是我这边网络的问题，但是这会导致保存图片error发不出消息，可以在保存图片时加个try except规避一下空图保存不了导致的错误？

**Comment by kexue-z** [comment]
如果风控的次数越来越多了 那就说明你离封号不远的

**Comment by huangusaki** [comment]
> 如果风控的次数再远那么说明你离封号不的

换了几个新号都有这问题的，那堆出问题的图片我自己的号发也是发送失败，缩放完图片啥事也没有了，所以推测是tx的自动审核问题

**Comment by kexue-z** [comment]
你可以试试改配置文件把图的尺寸缩小

或者你可以pr一个把图倒过来发的方法（

**Comment by kexue-z** [comment]
@Zzzzzzouhang 文档里面
![CleanShot 2022-06-07 at 16 28 06](https://user-images.githubusercontent.com/71873002/172334046-25939c30-d0f2-4220-9b30-c429e8bc2a8e.png)
