### ISSUE TITLE
涩图可不可以屏蔽单个群聊

### ISSUE THREAD

**Issue by memoriass** [kexue-z/nonebot-plugin-setu-now#29]
因为有大群有某些涩批经常要图，最近严打，导致频繁封号。但是其中很多人需要使用机器人功能，所以大佬有没有考虑增加一下这个功能。

**Comment by kexue-z** [comment]
https://github.com/nonepkg/nonebot-plugin-manager

**Comment by memoriass** [comment]
谢谢大佬
