### ISSUE TITLE
你好，这是什么情况？

### ISSUE THREAD

**Issue by xiangls** [kexue-z/nonebot-plugin-setu-now#3]
![QQ图片20220122173847](https://user-images.githubusercontent.com/67938770/150633350-e8685899-4e37-4d10-95d6-cd96609f8df7.png)

**Comment by kexue-z** [comment]
e，你用的b1还是a16？
b1的应该兼容了
--------------原始邮件--------------
发件人："XIaoZI ***@***.***&gt;;
发送时间：2022年1月22日(星期六) 下午5:37
收件人："kexue-z/nonebot-plugin-setu-now" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[kexue-z/nonebot-plugin-setu-now] 你好，这是什么情况？ (Issue #3)
-----------------------------------

 

 

 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xiangls** [comment]
b1
![QC{493UA9UEVK}6{~}H)2XP](https://user-images.githubusercontent.com/67938770/150633525-3e2729a8-1421-4f3e-9bae-35912b026c60.png)
的

**Comment by kexue-z** [comment]
插件版本呢？晚点我去看看

--------------原始邮件--------------
发件人："XIaoZI ***@***.***&gt;;
发送时间：2022年1月22日(星期六) 下午5:45
收件人："kexue-z/nonebot-plugin-setu-now" ***@***.***&gt;;
抄送："kexue ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [kexue-z/nonebot-plugin-setu-now] 你好，这是什么情况？ (Issue #3)
-----------------------------------

 

 
b1的
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kexue-z** [comment]
检查了一下 并没有这行代码
<img width="586" alt="CleanShot 2022-01-22 at 18 09 26@2x" src="https://user-images.githubusercontent.com/71873002/150634281-57cd08df-23c4-4c5a-a586-ad66d28d24a0.png">

建议更新插件版本
`0.0.4.3-beta.1`

**Comment by xiangls** [comment]
解决了，谢谢
