### ISSUE TITLE
无法使用tag搜索

### ISSUE THREAD

**Issue by if-u-can** [kexue-z/nonebot-plugin-setu-now#30]
比如输入指令setu tag 原神 甘雨  ，或者setu tag 原神 最后都会输出不相关图片

**Comment by kexue-z** [comment]
老bug了 还没修

**Comment by kexue-z** [comment]
咕咕咕 咕咕咕 咕咕咕咕咕

**Comment by forchannot** [comment]
所以解决了吗（

**Comment by kexue-z** [comment]
应该解决了 你测试一下~前几天有人PR了

**Comment by forchannot** [comment]
pypi还没更新吧，我刚重新装的还是不行

**Comment by kexue-z** [comment]
0.4.0 你看看 实在不行就直接用git源 `pip install git+https://github.com/kexue-z/nonebot-plugin-setu-now.git`

**Comment by forchannot** [comment]
git源貌似可以了，测试了十几张大多都符合tag，有些也许是api那边的问题

**Comment by kexue-z** [comment]
怎么测试的，能看看DEBUG的日志吗，，，我这都不对，，，

**Comment by forchannot** [comment]
debug日志我没开，我去开一下重启，稍等

**Comment by forchannot** [comment]
![image](https://user-images.githubusercontent.com/100580891/203545799-ec023cf5-3ea6-4b34-9d69-27fa6171af2f.png)

**Comment by kexue-z** [comment]
那行了 我更新下
