### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by misaka10032w** [kexue-z/nonebot-plugin-setu-now#31]
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_setu2\__init__.p
y", line 12, in <module>
    from nonebot.params import State
ImportError: cannot import name 'State' from 'nonebot.params' (C:\Users\Administrator\AppData\Local\Programs\Python\Pyth
on310\lib\site-packages\nonebot\params.py)
刚开始了解python，所以不太明白到底发生了什么，求助

**Comment by Cvandia** [comment]
尝试更新nonebot试试？

**Comment by kexue-z** [comment]
nb版本太新了 插件没有适配
