### ISSUE TITLE
图片发送失败

### ISSUE THREAD

**Issue by Cvandia** [kexue-z/nonebot-plugin-setu-now#32]
图片上传失败: image type error: application/octet-stream

**Comment by Cvandia** [comment]
就只发送文字描述，没有图片内容，控制台显示：图片上传失败: image type error: application/octet-stream

**Comment by n3wbeee** [comment]
我也遇到了这个问题，go-cqhttp 警告图片上传失败: image type error: application/octet-stream，插件未抛出错误

**Comment by uuKhost** [comment]
我这也有这个问题，终端报错相同，补两张图，不知道能不能帮助解决问题
![图片](https://user-images.githubusercontent.com/115860525/195970661-0d2b9d4a-081b-47d2-b3b3-a3d3d4d47f9d.png)
下面这张是我用浏览器进入了上面提到的网址
![图片](https://user-images.githubusercontent.com/115860525/195970620-984158e2-a14c-475b-ada2-e7a9da1b13e7.png)

**Comment by EtherLeaF** [comment]
貌似是镜像源裂开了。。如果没有本地图库目前还没找到解决方案

**Comment by qingba** [comment]
更改镜像源试试

**Comment by Cvandia** [comment]
找到新的api接口，希望作者大大更新下，感谢https://sex.nyan.xyz/

**Comment by kexue-z** [comment]
设置 `setu_reverse_proxy` 就行
