### ISSUE TITLE
私聊机器人时，本地保存图片的路径错误

### ISSUE THREAD

**Issue by mAjorHonxx** [kexue-z/nonebot-plugin-setu-now#34]
私聊机器人时，本地保存图片的路径错误。群聊时保存正常。
![image](https://user-images.githubusercontent.com/37525748/197385339-813de069-b6bc-4def-ad01-ca488ff55259.png)

**Comment by kexue-z** [comment]
你应该是自己改了默认路径的 建议把那个配置删了

**Comment by kexue-z** [comment]
哦 我知道了，没有创建好这个文件夹
手动创建就行

**Comment by mAjorHonxx** [comment]
> 哦 我知道了，没有创建好这个文件夹 手动创建就行

谢谢作者！原来r18是保存在另一个文件夹的，使用默认路径再新建一个setur18的文件夹就解决问题了。
