### ISSUE TITLE
这是怎么回事  我什么也没弄 突然间无法使用了

### ISSUE THREAD

**Issue by Wexevou** [kexue-z/nonebot-plugin-setu-now#35]
![QQ图片20221109233344](https://user-images.githubusercontent.com/117566653/200872882-30cf0ccc-17ce-4543-9445-da99a59b34f7.png)

**Comment by kexue-z** [comment]
可能是色图API炸了 最近都是这样 没办法

**Comment by Wexevou** [comment]
> 

更换个代理？还有作者有群嘛？进群好解决问题

**Comment by kexue-z** [comment]
你可以加入wq佬的682145034
