### ISSUE TITLE
No module named 'nonebot.adapters.cqhttp.permission'

### ISSUE THREAD

**Issue by huang1566** [kexue-z/nonebot-plugin-setu-now#4]
![image](https://user-images.githubusercontent.com/37030350/150663296-2cbae8d8-4e15-4ca1-945d-31c9864ad4cc.png)
cqhttp改名了 **好像**改成onebotv11adapter了 这边也要改改

**Comment by kexue-z** [comment]
这是什么版本的插件 最新支持beta1的版本是`0.0.4.3-beta.1` 建议升级一下

**Comment by huang1566** [comment]
手动导入就行了 改了源的pip(arm64)就是不更新（
