### ISSUE TITLE
禁用随机特效不能按预期工作

### ISSUE THREAD

**Issue by OREOCODEDEV** [kexue-z/nonebot-plugin-setu-now#40]
img_utils.py中randon_effect方法内

>     if effect:
>         func = funcs[1][effect]
>     else:
>         func = choices(population=funcs[1], weights=funcs[2], k=1)
>     output: Image.Image = func[0](_img)

当 effect == 0 时，会走else分支导致配置项`setu_add_randon_effect`不生效，且output赋值的索引[0]应该只对random.choices的结果进行索引，否则指定处理特效时会导致TypeError

**Comment by kexue-z** [comment]
立即PR

**Comment by OREOCODEDEV** [comment]
PR了，科佬康康有没有问题（
