### ISSUE TITLE
R18图片保存bug

### ISSUE THREAD

**Issue by Suxmx** [kexue-z/nonebot-plugin-setu-now#48]
![image](https://user-images.githubusercontent.com/33772816/221392812-da78867b-e052-4cff-a080-9bf856d3684a.png)
path这里的r18是不是前面要加'/'?

**Comment by kexue-z** [comment]
可以直接新建一个 setur18 的文件夹
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sun, Feb 26, 2023 12:47 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[kexue-z/nonebot-plugin-setu-now] R18图片保存bug (Issue #48)

&nbsp;



 

 path这里的r18是不是前面要加'/'?
