### ISSUE TITLE
请问一下 怎么添加R18白名单群组呢？

### ISSUE THREAD

**Issue by XiaoLong2333** [kexue-z/nonebot-plugin-setu-now#50]
RT，请问一下 怎么添加R18白名单群组呢？

**Comment by XiaoLong2333** [comment]
我发了可以色色以后机器人没有反应

**Comment by kexue-z** [comment]
什么版本？

**Comment by XiaoLong2333** [comment]
我不知道从哪里看版本，然后哪里可以更新呢

**Comment by XiaoLong2333** [comment]
我是在nonebot 那边商店导入的插件

**Comment by kexue-z** [comment]
那应该不是测试版，所以r18在群聊中是不可用的。默认关闭。也不能打开。除非你自己改代码。

**Comment by OREOCODEDEV** [comment]
啊，你可以在虚拟环境（如有）下使用`pip install git+https://github.com/kexue-z/nonebot-plugin-setu-now.git`安装`main`分支下的测试版本，或者等这两天~~我修修补补之后~~发布正式版本再使用`nb plugin install nonebot-plugin-setu-now --upgrade`升级到最新版

**Comment by XiaoLong2333** [comment]
好的吧我过几天在update！

**Comment by XiaoLong2333** [comment]
dd ,想问一下修好了吗（（

**Comment by XiaoLong2333** [comment]
看了一下版本号 还是0.4.4

**Comment by kexue-z** [comment]
你可以指定版本下载测试版

**Comment by kexue-z** [comment]
更新了 0.6.0.beta.1 快试试

**Comment by XiaoLong2333** [comment]
那我该怎么配置呢

**Comment by kexue-z** [comment]
在这个群里 超管发送 `/可以色色`
