### ISSUE TITLE
 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored

### ISSUE THREAD

**Issue by marswh12312313** [kexue-z/nonebot-plugin-setu-now#6]
私聊机器人 /色图 的无回复，返回此提示。
求解决。

[SUCCESS] nonebot | ONEBOT V11 XXX | [message.private.friend]: Message -280910093 from XXXXX "/色图"
[DEBUG] nonebot | Checking for matchers in priority 1...
[DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'> not match annotation GroupMessageEvent, ignored

**Comment by kexue-z** [comment]
色图

--------------原始邮件--------------
发件人："marswh12312313 ***@***.***&gt;;
发送时间：2022年2月1日(星期二) 中午11:01
收件人："kexue-z/nonebot-plugin-setu-now" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[kexue-z/nonebot-plugin-setu-now]  [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'&gt; not match annotation GroupMessageEvent, ignored (Issue #6)
-----------------------------------

 

 
私聊机器人 /色图 的无回复，返回此提示。
 求解决。
 
[SUCCESS] nonebot | ONEBOT V11 XXX | [message.private.friend]: Message -280910093 from XXXXX "/色图"
 [DEBUG] nonebot | Checking for matchers in priority 1...
 [DEBUG] nonebot | Event type <class 'nonebot.adapters.onebot.v11.event.PrivateMessageEvent'&gt; not match annotation GroupMessageEvent, ignored
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by marswh12312313** [comment]
已解决（我好蠢）
