### ISSUE TITLE
[Docs] 更新文档

### ISSUE THREAD

**Issue by yangjiaji1795** [kexue-z/nonebot-plugin-setu-now#61]
能不能发一个全部指令，那个文档只有色图的指令。感觉可以更新下文档了。

**Comment by kexue-z** [comment]
什么是 `全部指令`?

**Comment by yangjiaji1795** [comment]
就是指令加解释那种，像那个‘信息’指令我就没研究明白如何显示图片的信息。
还有不看lssues的话，我都不知道升级最新版开启群白名单。

**Comment by yangjiaji1795** [comment]
建议可以更新一下文档，这样对新手友好一些。

**Comment by kexue-z** [comment]
fixed https://github.com/kexue-z/nonebot-plugin-setu-now/commit/b894c9e1f20b64f338e49080a7f886edac2afd19
