### ISSUE TITLE
如何关闭模糊缩放

### ISSUE THREAD

**Issue by watershed117** [kexue-z/nonebot-plugin-setu-now#64]

**Comment by kexue-z** [comment]
在尝试原图发送失败的时候，会使用模糊缩放再次发送，以提高成功率。

经过测试这样是可以大量提高成功率的。

所以不建议关掉

**Comment by OREOCODEDEV** [comment]
模糊缩放是图片发送失败时的默认首选fallback方案，它并不支持单独关闭
`
EFFECT_FUNC_LIST = [do_nothing, draw_frame, random_flip, random_lines, random_rotate]
`

但你可以添加配置项`setu_add_random_effect=False`禁止对原图进行任何二次处理，此时如果发送失败将直接跳过该图片并记数为发送失败

**Comment by OREOCODEDEV** [comment]
发现在协议端无法访问NoneBot2图片路径时会导致入参文件路径方式发送直接失败，导致所有图片都被用于模糊缩放效果

你可以先添加配置项`SEND_AS_BYTES=True`强制以BytesIO发送原图，这样能确保只有发送失败的图片才会应用上模糊缩放效果

下一个版本会把这个配置项默认置True
