### ISSUE TITLE
怎么开启涩涩

### ISSUE THREAD

**Issue by nightcat2019** [kexue-z/nonebot-plugin-setu-now#68]
怎么操作开启涩涩？这里配置超管吗？
![image](https://github.com/user-attachments/assets/0fc2ce97-8a77-4f53-bcab-ebd8b071ab3e)

**Comment by kexue-z** [comment]
是

**Comment by nightcat2019** [comment]
> 是

管理员开启命令没生效

**Comment by nightcat2019** [comment]
谢谢，已经可以了
