### ISSUE TITLE
使用时报错module 'anyio' has no attribute 'Lock'

### ISSUE THREAD

**Issue by bingganhe123** [kexue-z/nonebot-plugin-setu-now#7]
如题，谢谢大佬

**Comment by bingganhe123** [comment]
这个脚本与python自带的脚本名字重复了

**Comment by bingganhe123** [comment]
> 请提供完整的LOG
> 
> ![image](https://user-images.githubusercontent.com/71873002/153707294-4e1e318d-2570-4e8e-8c08-e14f1b2b3d51.png)
![问题](https://user-images.githubusercontent.com/98812723/153707536-e76377d8-f407-46dc-8bd2-7071eb8f800a.png)

**Comment by bingganhe123** [comment]
> 提供完整的LOG
不好意思，少传了一张图，我用的是3.9
![问题1](https://user-images.githubusercontent.com/98812723/153715662-95fc602b-20aa-4b39-ab2d-aa558125c44c.png)
![问题2](https://user-images.githubusercontent.com/98812723/153715679-5cabf213-5454-4460-b455-6af7fcc13eaa.png)

**Comment by kexue-z** [comment]
目测是python环境出问题了 尝试使用venv 或者直接上poetry

--------------原始邮件--------------
发件人："bingganhe123 ***@***.***&gt;;
发送时间：2022年2月12日(星期六) 晚上10:39
收件人："kexue-z/nonebot-plugin-setu-now" ***@***.***&gt;;
抄送："kexue ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [kexue-z/nonebot-plugin-setu-now] 使用时报错module 'anyio' has no attribute 'Lock' (Issue #7)
-----------------------------------

 

  
提供完整的LOG
 不好意思，少传了一张图，我用的是3.9
 
 
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bingganhe123** [comment]
> 目测是python环境出问题了 尝试使用venv 或者直接上poetry
> […](#)
> --------------原始邮件-------------- 发件人："bingganhe123 ***@***.***&gt;; 发送时间：2022年2月12日(星期六) 晚上10:39 收件人："kexue-z/nonebot-plugin-setu-now" ***@***.***&gt;; 抄送："kexue ***@***.***&gt;;"Comment ***@***.***&gt;; 主题：Re: [kexue-z/nonebot-plugin-setu-now] 使用时报错module 'anyio' has no attribute 'Lock' (Issue #7) ----------------------------------- 提供完整的LOG 不好意思，少传了一张图，我用的是3.9 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

我重启了一下电脑，突然就可以运行了，不清楚为什么，现在运行一切正常，应该是电脑问题，谢谢大佬的指导，万分感谢！
