### ISSUE TITLE
希望能够增加一个屏蔽ai的可选项

### ISSUE THREAD

**Issue by longwindy** [kexue-z/nonebot-plugin-setu-now#70]
我研究了一下 https://api.lolicon.app/#/setu 这里的文档，看到在发送api请求的时候有个excludeAI的可选项，于是在我实装这个插件的时候曾尝试过在class Setu里面添加了一个excludeAI的成员
![image](https://github.com/user-attachments/assets/e9b5c871-2348-4d09-ae1d-d0c1e277b258)

但是在实际运行中发现这种方式并不能提供AI过滤，希望能提供可以屏蔽ai的可选项或者提供手动屏蔽ai的帮助，谢谢！

**Comment by longwindy** [comment]
笑死刚刚发现自己理解错了，刚刚在 `data_resource.py` 文件里面的 `SetuHandler` 类的 `refresh_api_info` 函数里面的data赋值加了 `"excludeAI": True` 这一字段后好像可以屏蔽ai图了

**Comment by kexue-z** [comment]
立即PR！

**Comment by kexue-z** [comment]
add in v0.6.5.1
