### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'setu_porxy'

### ISSUE THREAD

**Issue by AquamarineCyan** [kexue-z/nonebot-plugin-setu-now#8]
插件启动报错：AttributeError: 'Config' object has no attribute 'setu_porxy'
nonebot2.0.0-beta2

**Comment by kexue-z** [comment]
哦草 英文单词拼错了（

**Comment by AquamarineCyan** [comment]
阿这，等推包
另外nonebot2已经有beta2了，所以环境那里==b1会不会报错

**Comment by kexue-z** [comment]
确实 已经改了
